// ============================================================
// NxtStep — Landing Page
// ============================================================

import { Link } from 'react-router-dom';
import { ArrowRight, Zap, BarChart3, Target, Sparkles, CheckCircle2, Sun, Moon } from 'lucide-react';
import { useTheme } from '@/hooks';
import { usePageTitle } from '@/hooks';

const FEATURES = [
  {
    icon: <Zap className="w-5 h-5" />,
    title: 'AI-Powered Questions',
    desc: 'Real-time questions generated by advanced AI, calibrated to your role and experience level.',
    color: 'text-primary-500 bg-primary-500/10',
  },
  {
    icon: <BarChart3 className="w-5 h-5" />,
    title: 'Deep Evaluation',
    desc: 'Five-dimension scoring — technical depth, communication, problem-solving, confidence, and concept clarity.',
    color: 'text-secondary-500 bg-secondary-500/10',
  },
  {
    icon: <Target className="w-5 h-5" />,
    title: 'Role Recommendations',
    desc: 'Get matched to 45+ curated roles based on your scorecard, preferences, and industry salary data.',
    color: 'text-accent-500 bg-accent-500/10',
  },
  {
    icon: <Sparkles className="w-5 h-5" />,
    title: 'Personalised News Feed',
    desc: 'Hybrid-scored tech news from TechCrunch, Wired, and more — tailored to your interests.',
    color: 'text-emerald-500 bg-emerald-500/10',
  },
];

const PERKS = [
  'Real-time Socket.IO delivery',
  'Anti-cheat proctoring',
  'Follow-up questions on weak answers',
  'Scorecard radar chart',
  'Salary range data per role',
  'Dark & light theme',
];

export default function LandingPage() {
  usePageTitle('AI Interview Platform');
  const { isDark, toggle } = useTheme();

  return (
    <div className="min-h-screen flex flex-col bg-[var(--color-bg)]">
      {/* ── Navbar ─────────────────────────────────────────── */}
      <nav className="sticky top-0 z-30 border-b border-[var(--color-border)] bg-[var(--color-bg)]/80 backdrop-blur-md">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 h-14 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-xl bg-primary-500 flex items-center justify-center shadow-glow-sm">
              <span className="text-white font-display font-bold text-sm">N</span>
            </div>
            <span className="font-display font-bold text-base text-[var(--color-text-primary)]">NxtStep</span>
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={toggle}
              className="p-2 rounded-xl text-[var(--color-text-muted)] hover:bg-[var(--color-bg-elevated)] transition-colors"
              aria-label="Toggle theme"
            >
              {isDark ? <Sun size={18} /> : <Moon size={18} />}
            </button>
            <Link to="/login" className="btn-secondary text-sm px-4 py-2 h-9">
              Sign in
            </Link>
            <Link to="/register" className="btn-primary text-sm px-4 py-2 h-9">
              Get started
            </Link>
          </div>
        </div>
      </nav>

      {/* ── Hero ───────────────────────────────────────────── */}
      <section className="relative flex-1 flex flex-col items-center justify-center text-center px-4 py-24 overflow-hidden">
        {/* Background mesh */}
        <div className="absolute inset-0 bg-mesh pointer-events-none" />
        <div className="absolute top-20 -left-32 w-96 h-96 bg-primary-500/5 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute bottom-20 -right-32 w-96 h-96 bg-secondary-500/5 rounded-full blur-3xl pointer-events-none" />

        <div className="relative z-10 max-w-4xl mx-auto">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-primary-500/10 border border-primary-500/20 text-primary-500 text-sm font-medium mb-8 animate-fade-in">
            <Sparkles size={14} />
            AI-powered interview preparation
          </div>

          <h1 className="font-display font-bold text-4xl sm:text-5xl lg:text-6xl text-[var(--color-text-primary)] leading-tight mb-6 animate-slide-up">
            Land your dream role
            <br />
            with{' '}
            <span className="text-gradient">AI coaching</span>
          </h1>

          <p className="text-lg sm:text-xl text-[var(--color-text-secondary)] max-w-2xl mx-auto mb-10 leading-relaxed animate-slide-up animate-stagger-1">
            Practice real interviews, get five-dimension feedback, discover role matches, and stay sharp
            with a personalised tech news feed — all in one platform.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 animate-slide-up animate-stagger-2">
            <Link
              to="/register"
              className="btn-primary text-base px-7 py-3 h-12 gap-2 shadow-glow hover:shadow-glow-lg"
            >
              Start for free
              <ArrowRight size={18} />
            </Link>
            <Link to="/login" className="btn-secondary text-base px-7 py-3 h-12">
              Sign in
            </Link>
          </div>
        </div>
      </section>

      {/* ── Features Grid ──────────────────────────────────── */}
      <section className="py-20 px-4 bg-[var(--color-bg-secondary)]">
        <div className="max-w-6xl mx-auto">
          <h2 className="font-display font-bold text-3xl text-center text-[var(--color-text-primary)] mb-4">
            Everything you need to ace the interview
          </h2>
          <p className="text-[var(--color-text-secondary)] text-center max-w-xl mx-auto mb-12">
            From question generation to role matching — NxtStep covers the full interview prep lifecycle.
          </p>

          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {FEATURES.map((f, i) => (
              <div
                key={f.title}
                className="p-6 rounded-2xl bg-[var(--color-bg-card)] border border-[var(--color-border)] hover:-translate-y-1 transition-all duration-300 hover:shadow-lg"
                style={{ animationDelay: `${i * 0.1}s` }}
              >
                <div className={`w-10 h-10 rounded-xl flex items-center justify-center mb-4 ${f.color}`}>
                  {f.icon}
                </div>
                <h3 className="font-display font-semibold text-base text-[var(--color-text-primary)] mb-2">
                  {f.title}
                </h3>
                <p className="text-sm text-[var(--color-text-secondary)] leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Perks List ─────────────────────────────────────── */}
      <section className="py-20 px-4">
        <div className="max-w-2xl mx-auto text-center">
          <h2 className="font-display font-bold text-3xl text-[var(--color-text-primary)] mb-10">
            Built for serious candidates
          </h2>
          <ul className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-left">
            {PERKS.map((perk) => (
              <li key={perk} className="flex items-center gap-3">
                <CheckCircle2 size={18} className="text-emerald-500 shrink-0" />
                <span className="text-[var(--color-text-secondary)] text-sm">{perk}</span>
              </li>
            ))}
          </ul>
          <div className="mt-12">
            <Link to="/register" className="btn-primary text-base px-8 py-3 h-12 shadow-glow hover:shadow-glow-lg">
              Create free account
              <ArrowRight size={18} />
            </Link>
          </div>
        </div>
      </section>

      {/* ── Footer ─────────────────────────────────────────── */}
      <footer className="border-t border-[var(--color-border)] py-6 px-4 text-center">
        <p className="text-xs text-[var(--color-text-muted)]">
          © {new Date().getFullYear()} NxtStep — AI Interview Platform. All rights reserved.
        </p>
      </footer>
    </div>
  );
}
