// ============================================================
// NxtStep — Landing Page
// FIX: Auth-aware navbar — shows Profile when logged in, hides login/signup.
// ADDED: Rich entrance animations, hover effects, floating elements.
// ============================================================

import { Link } from 'react-router-dom';
import { ArrowRight, Zap, BarChart3, Target, Sparkles, CheckCircle2, Sun, Moon, User, LayoutDashboard } from 'lucide-react';
import { useTheme } from '@/hooks';
import { usePageTitle } from '@/hooks';
import { useAppSelector } from '@/app/hooks';
import { selectIsAuthenticated, selectCurrentUser } from '@/features/auth/authSlice';

const FEATURES = [
  {
    icon: <Zap className="w-5 h-5" />,
    title: 'AI-Powered Questions',
    desc: 'Real-time questions generated by advanced AI, calibrated to your role and experience level.',
    color: 'text-primary-500 bg-primary-500/10',
    delay: '0ms',
  },
  {
    icon: <BarChart3 className="w-5 h-5" />,
    title: 'Deep Evaluation',
    desc: 'Five-dimension scoring — technical depth, communication, problem-solving, confidence, and concept clarity.',
    color: 'text-secondary-500 bg-secondary-500/10',
    delay: '100ms',
  },
  {
    icon: <Target className="w-5 h-5" />,
    title: 'Role Recommendations',
    desc: 'Get matched to 45+ curated roles based on your scorecard, preferences, and industry salary data.',
    color: 'text-accent-500 bg-accent-500/10',
    delay: '200ms',
  },
  {
    icon: <Sparkles className="w-5 h-5" />,
    title: 'Personalised News Feed',
    desc: 'Hybrid-scored tech news from TechCrunch, Wired, and more — tailored to your interests.',
    color: 'text-emerald-500 bg-emerald-500/10',
    delay: '300ms',
  },
];

const PERKS = [
  'Real-time Socket.IO delivery',
  'Anti-cheat proctoring',
  'Follow-up questions on weak answers',
  'Scorecard radar chart',
  'Salary range data per role',
  'Dark & light theme',
];

export default function LandingPage() {
  usePageTitle('AI Interview Platform');
  const { isDark, toggle } = useTheme();
  const isAuthenticated = useAppSelector(selectIsAuthenticated);
  const user = useAppSelector(selectCurrentUser);

  return (
    <div className="min-h-screen flex flex-col bg-[var(--color-bg)] overflow-x-hidden">
      {/* ── Navbar ─────────────────────────────────────────── */}
      <nav className="sticky top-0 z-30 border-b border-[var(--color-border)] bg-[var(--color-bg)]/80 backdrop-blur-md">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 h-14 flex items-center justify-between">
          <div className="flex items-center gap-2.5 group">
            <div className="w-8 h-8 rounded-xl bg-primary-500 flex items-center justify-center shadow-glow-sm transition-all duration-300 group-hover:shadow-glow group-hover:scale-110">
              <span className="text-white font-display font-bold text-sm">N</span>
            </div>
            <span className="font-display font-bold text-base text-[var(--color-text-primary)]">NxtStep</span>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={toggle}
              className="p-2 rounded-xl text-[var(--color-text-muted)] hover:bg-[var(--color-bg-elevated)] hover:text-primary-500 transition-all duration-200 hover:scale-110"
              aria-label="Toggle theme"
            >
              {isDark ? <Sun size={18} /> : <Moon size={18} />}
            </button>

            {isAuthenticated ? (
              /* ── Logged-in state ── */
              <div className="flex items-center gap-2">
                <Link
                  to="/dashboard"
                  className="flex items-center gap-2 px-3 py-2 rounded-xl text-sm font-medium text-[var(--color-text-secondary)] hover:bg-[var(--color-bg-elevated)] hover:text-[var(--color-text-primary)] transition-all duration-200"
                >
                  <LayoutDashboard size={16} />
                  Dashboard
                </Link>
                <Link
                  to="/profile"
                  className="flex items-center gap-2 px-3 py-2 rounded-xl text-sm font-medium bg-primary-500/10 text-primary-500 hover:bg-primary-500/20 transition-all duration-200 hover:scale-105"
                >
                  <div className="w-6 h-6 rounded-full bg-primary-500 flex items-center justify-center text-white font-bold text-xs">
                    {user?.name?.charAt(0).toUpperCase() || <User size={12} />}
                  </div>
                  {user?.name?.split(' ')[0] || 'Profile'}
                </Link>
              </div>
            ) : (
              /* ── Guest state ── */
              <>
                <Link to="/login" className="btn-secondary text-sm px-4 py-2 h-9 transition-all duration-200 hover:scale-105 hover:border-primary-400">
                  Sign in
                </Link>
                <Link to="/register" className="btn-primary text-sm px-4 py-2 h-9 transition-all duration-200 hover:scale-105 hover:shadow-glow">
                  Get started
                </Link>
              </>
            )}
          </div>
        </div>
      </nav>

      {/* ── Hero ───────────────────────────────────────────── */}
      <section className="relative flex-1 flex flex-col items-center justify-center text-center px-4 py-24 overflow-hidden">
        {/* Animated background blobs */}
        <div className="absolute inset-0 bg-mesh pointer-events-none" />
        <div className="absolute top-20 -left-32 w-96 h-96 bg-primary-500/8 rounded-full blur-3xl pointer-events-none animate-pulse" style={{ animationDuration: '4s' }} />
        <div className="absolute bottom-20 -right-32 w-96 h-96 bg-secondary-500/8 rounded-full blur-3xl pointer-events-none animate-pulse" style={{ animationDuration: '6s' }} />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-accent-500/3 rounded-full blur-3xl pointer-events-none animate-pulse" style={{ animationDuration: '8s' }} />

        {/* Floating decorative elements */}
        <div className="absolute top-24 left-[10%] w-3 h-3 rounded-full bg-primary-400/40 animate-bounce" style={{ animationDelay: '0ms', animationDuration: '3s' }} />
        <div className="absolute top-40 right-[15%] w-2 h-2 rounded-full bg-accent-400/40 animate-bounce" style={{ animationDelay: '500ms', animationDuration: '4s' }} />
        <div className="absolute bottom-32 left-[20%] w-2 h-2 rounded-full bg-secondary-400/40 animate-bounce" style={{ animationDelay: '1000ms', animationDuration: '3.5s' }} />
        <div className="absolute top-56 left-[30%] w-1.5 h-1.5 rounded-full bg-emerald-400/40 animate-bounce" style={{ animationDelay: '700ms', animationDuration: '5s' }} />

        <div className="relative z-10 max-w-4xl mx-auto">
          <div
            className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-primary-500/10 border border-primary-500/20 text-primary-500 text-sm font-medium mb-8 animate-fade-in hover:bg-primary-500/15 hover:scale-105 transition-all duration-300 cursor-default"
            style={{ animationDelay: '0ms' }}
          >
            <Sparkles size={14} className="animate-pulse" />
            AI-powered interview preparation
          </div>

          <h1
            className="font-display font-bold text-4xl sm:text-5xl lg:text-6xl text-[var(--color-text-primary)] leading-tight mb-6 animate-slide-up"
            style={{ animationDelay: '100ms', animationFillMode: 'both' }}
          >
            Land your dream role
            <br />
            with{' '}
            <span className="text-gradient relative">
              AI coaching
              <span className="absolute -bottom-1 left-0 right-0 h-0.5 bg-gradient-to-r from-primary-500 to-secondary-500 rounded-full opacity-60" />
            </span>
          </h1>

          <p
            className="text-lg sm:text-xl text-[var(--color-text-secondary)] max-w-2xl mx-auto mb-10 leading-relaxed animate-slide-up"
            style={{ animationDelay: '200ms', animationFillMode: 'both' }}
          >
            Practice real interviews, get five-dimension feedback, discover role matches, and stay sharp
            with a personalised tech news feed — all in one platform.
          </p>

          <div
            className="flex flex-col sm:flex-row items-center justify-center gap-4 animate-slide-up"
            style={{ animationDelay: '300ms', animationFillMode: 'both' }}
          >
            {isAuthenticated ? (
              <Link
                to="/interview/new"
                className="btn-primary text-base px-7 py-3 h-12 gap-2 shadow-glow hover:shadow-glow-lg hover:scale-105 transition-all duration-300"
              >
                <Zap size={18} />
                Start Interview
                <ArrowRight size={18} />
              </Link>
            ) : (
              <>
                <Link
                  to="/register"
                  className="btn-primary text-base px-7 py-3 h-12 gap-2 shadow-glow hover:shadow-glow-lg hover:scale-105 transition-all duration-300"
                >
                  Start for free
                  <ArrowRight size={18} />
                </Link>
                <Link to="/login" className="btn-secondary text-base px-7 py-3 h-12 hover:scale-105 transition-all duration-300">
                  Sign in
                </Link>
              </>
            )}
          </div>

          {/* Stats row */}
          <div
            className="flex items-center justify-center gap-8 mt-12 animate-fade-in"
            style={{ animationDelay: '500ms', animationFillMode: 'both' }}
          >
            {[
              { value: '45+', label: 'Role Templates' },
              { value: '5', label: 'Scoring Dimensions' },
              { value: '10', label: 'Questions / Session' },
            ].map(({ value, label }) => (
              <div key={label} className="text-center group cursor-default">
                <p className="font-display font-bold text-2xl text-gradient group-hover:scale-110 transition-transform duration-300 inline-block">{value}</p>
                <p className="text-xs text-[var(--color-text-muted)] mt-0.5">{label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Features Grid ──────────────────────────────────── */}
      <section className="py-20 px-4 bg-[var(--color-bg-secondary)]">
        <div className="max-w-6xl mx-auto">
          <h2 className="font-display font-bold text-3xl text-center text-[var(--color-text-primary)] mb-4 animate-fade-in">
            Everything you need to ace the interview
          </h2>
          <p className="text-[var(--color-text-secondary)] text-center max-w-xl mx-auto mb-12 animate-fade-in">
            From question generation to role matching — NxtStep covers the full interview prep lifecycle.
          </p>

          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {FEATURES.map((f) => (
              <div
                key={f.title}
                className="p-6 rounded-2xl bg-[var(--color-bg-card)] border border-[var(--color-border)] hover:-translate-y-2 hover:shadow-lg hover:border-primary-500/30 transition-all duration-300 cursor-default group"
                style={{ animationDelay: f.delay }}
              >
                <div className={`w-10 h-10 rounded-xl flex items-center justify-center mb-4 ${f.color} group-hover:scale-110 transition-transform duration-300`}>
                  {f.icon}
                </div>
                <h3 className="font-display font-semibold text-base text-[var(--color-text-primary)] mb-2 group-hover:text-primary-500 transition-colors duration-200">
                  {f.title}
                </h3>
                <p className="text-sm text-[var(--color-text-secondary)] leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Perks List ─────────────────────────────────────── */}
      <section className="py-20 px-4">
        <div className="max-w-2xl mx-auto text-center">
          <h2 className="font-display font-bold text-3xl text-[var(--color-text-primary)] mb-10">
            Built for serious candidates
          </h2>
          <ul className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-left">
            {PERKS.map((perk, i) => (
              <li
                key={perk}
                className="flex items-center gap-3 group hover:translate-x-1 transition-transform duration-200"
                style={{ animationDelay: `${i * 80}ms` }}
              >
                <CheckCircle2 size={18} className="text-emerald-500 shrink-0 group-hover:scale-110 transition-transform duration-200" />
                <span className="text-[var(--color-text-secondary)] text-sm group-hover:text-[var(--color-text-primary)] transition-colors duration-200">{perk}</span>
              </li>
            ))}
          </ul>
          <div className="mt-12">
            {isAuthenticated ? (
              <Link
                to="/interview/new"
                className="btn-primary text-base px-8 py-3 h-12 shadow-glow hover:shadow-glow-lg hover:scale-105 transition-all duration-300"
              >
                <Zap size={18} />
                Start Interview Now
                <ArrowRight size={18} />
              </Link>
            ) : (
              <Link
                to="/register"
                className="btn-primary text-base px-8 py-3 h-12 shadow-glow hover:shadow-glow-lg hover:scale-105 transition-all duration-300"
              >
                Create free account
                <ArrowRight size={18} />
              </Link>
            )}
          </div>
        </div>
      </section>

      {/* ── Footer ─────────────────────────────────────────── */}
      <footer className="border-t border-[var(--color-border)] py-6 px-4 text-center">
        <p className="text-xs text-[var(--color-text-muted)]">
          © {new Date().getFullYear()} NxtStep — AI Interview Platform. All rights reserved.
        </p>
      </footer>
    </div>
  );
}